
import com.mysql.jdbc.PreparedStatement;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Booking extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        
        lbla1.addMouseListener(this);
        lbla2.addMouseListener(this);
        lbla3.addMouseListener(this);
        lblb1.addMouseListener(this);
        lblb2.addMouseListener(this);
        lblb3.addMouseListener(this);
        lblc1.addMouseListener(this);
        lblc2.addMouseListener(this);
        lblc3.addMouseListener(this);
        lbld1.addMouseListener(this);
        lbld2.addMouseListener(this);
        lbld3.addMouseListener(this);
        lble1.addMouseListener(this);
        lble2.addMouseListener(this);
        lble3.addMouseListener(this);
        lblf1.addMouseListener(this);
         lblf2.addMouseListener(this);
          lblf3.addMouseListener(this);
           lblg1.addMouseListener(this);
            lblg2.addMouseListener(this);
             lblg3.addMouseListener(this);
              lblh1.addMouseListener(this);
              lblh2.addMouseListener(this);
              lblh3.addMouseListener(this);
             autoID();
             Date date=new Date();
        txtdate.getDayChooser().setMinSelectableDate(date);
             
             
        }
  int seat =0;
  public void print(){
      String   ID= txtid.getText();
      String customer=txtname.getText();
      int seat1=seat;
      String price =txtprice.getText();

SimpleDateFormat date_form=new SimpleDateFormat("yyyy-MM-dd");
String Date=date_form.format(txtdate.getDate());

   txtbill.setText(txtbill.getText() +   "*****    Ticket ****** \n");
    txtbill.setText(txtbill.getText() +  "Customer ID :"+"\t" +ID +"\n");
txtbill.setText(txtbill.getText() +  "Customer Name :"+"\t" +customer +"\n");
txtbill.setText(txtbill.getText() +  "Seat No :"+"\t" +seat1+"\n");
txtbill.setText(txtbill.getText() +  "Ticket Price :"+"\t" +price +"\n");
txtbill.setText(txtbill.getText() +  "Date"+"\t" +Date+"\n");


  }
  
  public void autoID()
   {
    
        try {
            Class.forName("java.sql.DriverManager");
             Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bus","root","");
             Statement stmt=(Statement)con.createStatement();
            ResultSet rs=stmt.executeQuery("select max(ID) FROM bus_booking ");
           rs.next();
         String t =rs.getString("MAX(ID)");
          if(t==null )
           {
             txtid.setText("C00001");

               }
          else  {
             long id=Long.parseLong(rs.getString("MAX(ID)").substring(1,rs.getString("MAX(ID)").length()));
             id++;
            txtid.setText("C" +String.format("%05d",id));

                }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
       
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbla1 = new javax.swing.JLabel();
        lbla2 = new javax.swing.JLabel();
        lbla3 = new javax.swing.JLabel();
        lblb1 = new javax.swing.JLabel();
        lblb2 = new javax.swing.JLabel();
        lblb3 = new javax.swing.JLabel();
        lblc1 = new javax.swing.JLabel();
        lblc2 = new javax.swing.JLabel();
        lblc3 = new javax.swing.JLabel();
        lbld1 = new javax.swing.JLabel();
        lbld2 = new javax.swing.JLabel();
        lbld3 = new javax.swing.JLabel();
        lble1 = new javax.swing.JLabel();
        lble2 = new javax.swing.JLabel();
        lble3 = new javax.swing.JLabel();
        lblf1 = new javax.swing.JLabel();
        lblf2 = new javax.swing.JLabel();
        lblf3 = new javax.swing.JLabel();
        lblg1 = new javax.swing.JLabel();
        lblg2 = new javax.swing.JLabel();
        lblg3 = new javax.swing.JLabel();
        lblh3 = new javax.swing.JLabel();
        lblh2 = new javax.swing.JLabel();
        lblh1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Desh Travels Ticket Booking System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name :");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        lbla1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbla1.setText("A1");

        lbla2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbla2.setText("A2");

        lbla3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbla3.setText("A3");

        lblb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblb1.setText("B1");

        lblb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblb2.setText("B2");

        lblb3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblb3.setText("B3");

        lblc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblc1.setText("C1");

        lblc2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblc2.setText("C2");

        lblc3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblc3.setText("C3");

        lbld1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbld1.setText("D1");

        lbld2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbld2.setText("D2");

        lbld3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbld3.setText("D3");

        lble1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lble1.setText("E1");

        lble2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lble2.setText("E2");

        lble3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lble3.setText("E3");

        lblf1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblf1.setText("F1");

        lblf2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblf2.setText("F2");

        lblf3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblf3.setText("F3");

        lblg1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblg1.setText("G1");

        lblg2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblg2.setText("G2");

        lblg3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblg3.setText("G3");

        lblh3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblh3.setText("H3");

        lblh2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblh2.setText("H2");

        lblh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblh1.setText("H1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbla3)
                        .addGap(18, 18, 18)
                        .addComponent(lblb3)
                        .addGap(18, 18, 18)
                        .addComponent(lblc3)
                        .addGap(18, 18, 18)
                        .addComponent(lbld3)
                        .addGap(18, 18, 18)
                        .addComponent(lble3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblf3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbla1)
                                .addGap(18, 18, 18)
                                .addComponent(lblb1)
                                .addGap(18, 18, 18)
                                .addComponent(lblc1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbla2)
                                .addGap(18, 18, 18)
                                .addComponent(lblb2)
                                .addGap(18, 18, 18)
                                .addComponent(lblc2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbld2)
                            .addComponent(lbld1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lble2)
                            .addComponent(lble1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblf1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblf2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblg2)
                        .addGap(18, 18, 18)
                        .addComponent(lblh2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblg1)
                        .addGap(18, 18, 18)
                        .addComponent(lblh1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblg3)
                        .addGap(18, 18, 18)
                        .addComponent(lblh3)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lble1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbla1)
                        .addComponent(lblb1)
                        .addComponent(lblc1)
                        .addComponent(lblf1)
                        .addComponent(lblg1)
                        .addComponent(lblh1)
                        .addComponent(lbld1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbla2)
                            .addComponent(lblb2)
                            .addComponent(lblc2)
                            .addComponent(lbld2)
                            .addComponent(lble2)
                            .addComponent(lblf2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblh2)
                            .addComponent(lblg2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbla3)
                    .addComponent(lblb3)
                    .addComponent(lblc3)
                    .addComponent(lbld3)
                    .addComponent(lble3)
                    .addComponent(lblf3)
                    .addComponent(lblg3)
                    .addComponent(lblh3))
                .addGap(21, 21, 21))
        );

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Seat");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Price :");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtbill.setBackground(new java.awt.Color(51, 255, 255));
        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Id:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Check Ticket ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Print ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(108, 108, 108)))
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3)
                                        .addGap(28, 28, 28))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel27))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jButton1)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
              Connection  con=(Connection)
             DriverManager.getConnection("jdbc:mysql://localhost:3306/bus","root","");
              String   ID= txtid.getText();
              String customer=txtname.getText();
              int seat1=seat;
              String price =txtprice.getText();
              SimpleDateFormat date_form=new SimpleDateFormat("yyyy-MM-dd");
               String Date=date_form.format(txtdate.getDate());
               PreparedStatement pst=(PreparedStatement) con.prepareStatement("select * from bus_booking where date=? and seat_no=?");
             pst.setString(1,Date);
            pst.setInt(2,seat1);
            ResultSet rs=pst.executeQuery();
              if(rs.next()==true){
            JOptionPane.showMessageDialog(this,"This Seat Already Booked");
          }
else{
       pst=(PreparedStatement) con.prepareStatement("insert into bus_booking(id,customer_name,seat_no,price,date) values (?,?,?,?,?)");
       pst.setString(1,ID);
       pst.setString(2,customer);
       pst.setInt(3,seat1);
       pst.setString(4,price);
       pst.setString(5,Date);
      int k=pst.executeUpdate();
         if(k==1){
            JOptionPane.showMessageDialog(this,"Seat Booked");
            print();
           }
           else{
              JOptionPane.showMessageDialog(this,"Some Thing Wrong");
             }

}

       
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
         ;
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       check c=new check();
       c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {      
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbla1;
    private javax.swing.JLabel lbla2;
    private javax.swing.JLabel lbla3;
    private javax.swing.JLabel lblb1;
    private javax.swing.JLabel lblb2;
    private javax.swing.JLabel lblb3;
    private javax.swing.JLabel lblc1;
    private javax.swing.JLabel lblc2;
    private javax.swing.JLabel lblc3;
    private javax.swing.JLabel lbld1;
    private javax.swing.JLabel lbld2;
    private javax.swing.JLabel lbld3;
    private javax.swing.JLabel lble1;
    private javax.swing.JLabel lble2;
    private javax.swing.JLabel lble3;
    private javax.swing.JLabel lblf1;
    private javax.swing.JLabel lblf2;
    private javax.swing.JLabel lblf3;
    private javax.swing.JLabel lblg1;
    private javax.swing.JLabel lblg2;
    private javax.swing.JLabel lblg3;
    private javax.swing.JLabel lblh1;
    private javax.swing.JLabel lblh2;
    private javax.swing.JLabel lblh3;
    private javax.swing.JTextArea txtbill;
    private com.toedter.calendar.JCalendar txtdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
              if(e.getSource()==lbla1)
{
   seat=1;
} //To change body of generated methods, choose Tools | Templates.
        else if(e.getSource()==lbla2)
{
   seat=2;
   
} //To change body of generated methods, choose Tools | Templates.
   
            else if(e.getSource()==lbla3)
{
   seat=3;
} 
          else if(e.getSource()==lblb1)
{
   seat=4;
} 
   else if(e.getSource()==lblb2)
{
   seat=5;
} 
        else if(e.getSource()==lblb3)
{
   seat=6;
} 
            else if(e.getSource()==lblc1)
{
   seat=7;
} 
             else if(e.getSource()==lblc2)
{
   seat=8;
} 
             else if(e.getSource()==lblc3)
{
   seat=9;
} 
 else if(e.getSource()==lbld1)
{
   seat=10;
} 
         else if(e.getSource()==lbld2)
{
   seat=11;
} 
         else if(e.getSource()==lbld3)
{
   seat=12;
} 
          else if(e.getSource()==lble1)
{
   seat=13;
} 
       
         else if(e.getSource()==lble2)
{
   seat=14;
} 
         else if(e.getSource()==lble3)
{
   seat=15;
} 
        else if(e.getSource()==lblf1)
{
   seat=16;
} 
         else if(e.getSource()==lblf2)
{
   seat=17;
} 
         else if(e.getSource()== lblf3)
{
   seat=18;
} 
        else if(e.getSource()== lblg1)
{
   seat=19;
} 
        else if(e.getSource()== lblg2)
{
   seat=20;
} 
        else if(e.getSource()==lblg3)
{
   seat=21;
} 
        else if(e.getSource()==lblh1)
{
   seat=22;
} 
            else if(e.getSource()==lblh2)
{
   seat=23;
} 
    
                else if(e.getSource()==lblh3)
{
   seat=24;
} 
  JOptionPane.showMessageDialog(this,"Your Choice Seat No"+seat);
    }

    @Override
    public void mousePressed(MouseEvent e) {
       
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
       
    }

   
}
